Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -36,13 +36,14 @@ jobs:
       - name: Build data.table from source (if artifact not found)
         if: env.artifact_exists == 'false'
         run: |
-          Rscript -e "install.packages('data.table', version = '${{ env.VERSION }}', repos = 'http://cran.rstudio.com')"
-      - name: Create tarball
-        run: |
-         mkdir -p data.table
-         cp -r /tmp/RtmpDkq1T4/downloaded_packages/data.table data.table/
-         tar -czvf data.table.tar.gz data.table/
-
+         echo "Checking artifact existence: ${{ env.artifact_exists }}"
+         Rscript -e "install.packages('data.table', version = '${{ env.VERSION }}', repos = 'http://cran.rstudio.com')"
+         - name: Create tarball
+          run: |
+          PKG_PATH=$(Rscript -e "cat(system.file(package='data.table'))")[ -z "$PKG_PATH" ] && { echo "Error: data.table not found!"; exit 1; }
+          mkdir -p data.table && cp -r "$PKG_PATH" data.table/
+          tar -czvf data.table.tar.gz data.table/
+         shell: bash
       - name: Upload artifact for future use
         if: env.artifact_exists == 'false'
         uses: actions/upload-artifact@v4
